---
version: '3.9'
services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: always
    ports:
    - "443:443"
    depends_on:
    - gerrit
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - outputs:/var/www/outputs:ro
    - ${NGINX_CERT_DIR:-/etc/letsencrypt}:/etc/letsencrypt:ro
    - ${NGINX_STATIC_DIR:-/var/www/ci.spdk.io}:/var/www/localhost:ro
    networks:
    - gerrit

  gerrit:
    image: gerritcodereview/gerrit:3.13.4
    container_name: gerrit
    restart: always
    volumes:
    - ${GERRIT_DIR}/cache:/var/gerrit/cache
    - ${GERRIT_DIR}/data:/var/gerrit/data
    - ${GERRIT_DIR}/db:/var/gerrit/db
    - ${GERRIT_DIR}/etc:/var/gerrit/etc
    - ${GERRIT_DIR}/events-db:/var/gerrit/events-db
    - ${GERRIT_DIR}/git:/var/gerrit/git
    - ${GERRIT_DIR}/index:/var/gerrit/index
    - ${GERRIT_DIR}/lib:/var/gerrit/lib
    - ${GERRIT_DIR}/logs:/var/gerrit/logs
    - ${GERRIT_DIR}/plugins:/var/gerrit/plugins
    - ${GERRIT_DIR}/static:/var/gerrit/static
    - ${GERRIT_DIR}/tmp:/var/gerrit/tmp
    - ${GERRIT_DIR}/.ssh:/var/gerrit/.ssh
    env_file: ".env"
    environment:
    - CANONICAL_WEB_URL=${GERRIT_URL}
    ports:
    - "29418:29418"
    - "8080:8080"
    networks:
    - gerrit

  forwarder:
    image: forwarder:latest
    build:
      context: ./forwarder
      dockerfile: Dockerfile
    container_name: webhook_forwarder
    restart: always
    env_file:
    - .env
    - .env.forwarder
    depends_on:
    - gerrit
    volumes:
    - logs:/var/log
    - outputs:/output
    networks:
    - gerrit

  mergable_changes:
    image: mergable_changes:latest
    build:
      context: ./mergable_changes
      dockerfile: Dockerfile
    container_name: mergable_changes
    restart: always
    env_file: ".env"
    depends_on:
    - gerrit
    volumes:
    - logs:/var/log
    - outputs:/output
    networks:
    - gerrit

volumes:
  logs:
  outputs:

networks:
  gerrit:
    driver: bridge
