---
version: '3.9'
services:
  gerrit:
    image: gerritcodereview/gerrit:3.13.3
    container_name: gerrit
    restart: always
    volumes:
    - ${GERRIT_DIR}/cache:/var/gerrit/cache
    - ${GERRIT_DIR}/data:/var/gerrit/data
    - ${GERRIT_DIR}/db:/var/gerrit/db
    - ${GERRIT_DIR}/etc:/var/gerrit/etc
    - ${GERRIT_DIR}/events-db:/var/gerrit/events-db
    - ${GERRIT_DIR}/git:/var/gerrit/git
    - ${GERRIT_DIR}/index:/var/gerrit/index
    - ${GERRIT_DIR}/lib:/var/gerrit/lib
    - ${GERRIT_DIR}/logs:/var/gerrit/logs
    - ${GERRIT_DIR}/plugins:/var/gerrit/plugins
    - ${GERRIT_DIR}/static:/var/gerrit/static
    - ${GERRIT_DIR}/tmp:/var/gerrit/tmp
    - ${GERRIT_DIR}/.ssh:/var/gerrit/.ssh
    environment:
    - CANONICAL_WEB_URL=${GERRIT_CANONICAL_WEB_URL}
    ports:
    - "29418:29418"
    - "8080:8080"
    networks:
    - gerrit

  forwarder:
    image: forwarder:latest
    build:
      context: ./forwarder
      dockerfile: Dockerfile
    container_name: webhook_forwarder
    restart: always
    environment:
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    - GITHUB_REPO_URL=${GITHUB_REPO_URL}
    - TEST_MODE=${FORWARDER_TEST_MODE}
    depends_on:
    - gerrit
    volumes:
    - forwarder_logs:/var/log
    networks:
    - gerrit

  mergable_changes:
    image: mergable_changes:latest
    build:
      context: ./mergable_changes
      dockerfile: Dockerfile
    container_name: mergable_changes
    restart: always
    environment:
    - OUTPUT_DIR=${MERGABLE_CHANGES_OUTPUT_DIR}
    depends_on:
    - gerrit
    volumes:
    - mergable_changes_logs:/var/log
    - mergable_changes_out:/output
    networks:
    - gerrit

volumes:
  forwarder_logs:
  mergable_changes_logs:
  mergable_changes_out:

networks:
  gerrit:
    driver: bridge
