server {
    listen 443 ssl;
    server_name review.spdk.io;

    if ($http_user_agent ~* (ImagesiftBot|Bytespider|GPTBot|bingbot|Petalbot|SemrushBot|DuckAssistBot) ) {
        return 403;
    }

    ssl_certificate /etc/letsencrypt/live/localhost/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;
    ssl_protocols       TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location /download/ {
        root /var/www/localhost/;
        autoindex on;
    }

    location = /mergable_changes.html {
        alias /var/www/outputs/mergable_changes.html;
    }

    location = /mergable_changes.txt {
        alias /var/www/outputs/mergable_changes.txt;
    }

    location = /queue_status.html {
        alias /var/www/outputs/queue_status.html;
    }

    location /checks-api/ {
        proxy_pass        http://checks_api:8001/checks-api/;
        proxy_set_header  X-Forwarded-For $remote_addr;
        proxy_set_header  Host $host;
    }

    location /gerrit {
        rewrite ^/gerrit/(.*) /$1 permanent;
        proxy_pass        http://gerrit:8080;
        proxy_set_header  X-Forwarded-For $remote_addr;
        proxy_set_header  Host $host;
    }

    location ^~ / {
        proxy_pass        http://gerrit:8080;
        proxy_set_header  X-Forwarded-For $remote_addr;
        proxy_set_header  Host $host;
    }
}

server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
